{
    'name': 'ATC - Visitas Técnicas',
    'version': '19.0.2.8.0',
    'summary': 'Control de visitas técnicas a clientes de ISPs sobre Actividades',
    'description': 'Extiende las Actividades estandar (mail.activity) para que ATC controle visitas tecnicas a clientes de ISPs: tipo de actividad, campos (cedula con autocompletado de nombre, zona, etiquetas, estado), filtros, menu propio y un rol kiosko.',
    'category': 'Services',
    'author': 'Ing Pablo Ramìrez',
    'depends': ['mail', 'contacts', 'calendar', 'project_todo', 'hr', 'fleet', 'noc_guardias'],
    'data': [
        'security/atc_security.xml',
        'security/ir.model.access.csv',
        'data/activity_type.xml',
        'views/res_partner_views.xml',
        'views/atc_zona_views.xml',
        'views/atc_visita_tag_views.xml',
        'views/atc_visita_views.xml',
        'views/fleet_vehicle_views.xml',
        'views/atc_menus.xml',
        'views/menu_overrides.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
