[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$ztm7F6LU2huDECIkpDQmhA$GbgKYToJQQuSSNTGx4hYSlhZeAxRC3rH3lr4g9b9HyvdrCP/YrVwv5x.l6HOuh50nHCpYGzS.y0BZznKj1aPPQ
limit_time_cpu = 300000
limit_time_real = 300000
